fix arm build warning due to new compiler optimizations (#11362)
Build fails with warnings in ARM CI after adding more aggressive optimizations (#11350)
probably a result of more aggressive inlining

```
ziplist.c: In function ‘pop.constprop’:
ziplist.c:1770:13: error: ‘vlong’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
             printf("%lld", vlong);
             ^~~~~~~~~~~~~~~~~~~~~
```

```
listpack.c: In function ‘lpInsert.constprop’:
listpack.c:406:9: error: argument 2 null where non-null expected [-Werror=nonnull]
         memcpy(buf+1,s,len);
         ^~~~~~~~~~~~~~~~~~~
```